[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "0.57.2"

[context.deploy-preview.environment]
HUGO_VERSION = "0.57.2"

[context.deploy-preview]
  command = "npm run build:preview"